name: "My Conjur Action"
description: "Takes USER input and performs a task"
inputs:
  USER:
    description: "Username from Conjur"
    required: true
runs:
  using: "composite"
  steps:
    - name: Print user
      shell: bash
      run: echo "USER is ${{ inputs.USER }}"
