name: Terraform Workflow
 
on:
  workflow_call:
    inputs:
      secret-path:
        required: true
        type: string
    secrets:
      CONJUR_API_KEY:
        required: true
 
jobs:
  run-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Run Conjur Action
        uses: testid1/ConjurAPI/.github/actions/conjur@main
        with:
          CONJUR_API_KEY: ${{ secrets.CONJUR_API_KEY }}
          secret-path: ${{ inputs.secret-path }}
