name: Fetch Conjur Secret
 
on:
  workflow_call:
    inputs:
      secretpath:
        required: true
        type: string
    secrets:
      CONJUR_API_KEY: 
        required: true
 
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Install curl and jq
        run: sudo apt-get update && sudo apt-get install -y curl jq
 
      - name: Authenticate to Conjur and retrieve secret
        env:
          CONJUR_ACCOUNT: conjur
          CONJUR_APPLIANCE_URL: https://pwclab.secretsmgr.cyberark.cloud
          CONJUR_AUTHN_LOGIN: host%2Fdata%2Fgithub-app
          CONJUR_API_KEY: ${{ secrets.CONJUR_API_KEY }}   # ✅ secret from reusable repo
          SECRET_PATH: ${{ inputs.secretpath }}
        run: |
          set -e
          echo "==============================="
          echo "Logging into Conjur..."
          echo "Account: $CONJUR_ACCOUNT"
          echo "Appliance URL: $CONJUR_APPLIANCE_URL"
          echo "Authn Login: $CONJUR_AUTHN_LOGIN"
          echo "==============================="
 
          echo "Authenticating..."
          FULL_AUTHN_URL=$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate
          AUTHN_TOKEN=$(curl -s -k --request POST \
            --data "$CONJUR_API_KEY" \
            "$FULL_AUTHN_URL" | base64 | tr -d '\r\n')
          echo "Authentication successful"
          echo "==============================="
 
          echo "Fetching secret at: $SECRET_PATH"
          SECRET=$(curl -s -k --header "Authorization: Token token=\"$AUTHN_TOKEN\"" \
            "$CONJUR_APPLIANCE_URL/api/secrets/$CONJUR_ACCOUNT/variable/$SECRET_PATH")
 
          echo "Retrieved secret: $SECRET"
