name: Fetch Conjur Secret
 
on:
 workflow_call:
   inputs:
     secretpath:
        required: true
        type: string
 # push:
 #   branches: [ main ]
 
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Install curl and jq
      run: sudo apt-get update && sudo apt-get install -y curl jq
 
    - name: Authenticate to Conjur and retrieve secret
      env:
        CONJUR_ACCOUNT: conjur
        CONJUR_APPLIANCE_URL: https://pwclab.secretsmgr.cyberark.cloud
        CONJUR_AUTHN_LOGIN: host%2Fdata%2Fgithub-app
        CONJUR_API_KEY: ${{ secrets.CONJUR_API_KEY }}
        SECRET_PATH: ${{ inputs.secretpath }}
      #  CONJUR_API_KEY: 1pfa2en2cvh9q53xwymqc2fhehge303h3gt1jw2ppj1xweg0831exsd7
      run: |
        set -e
 
        echo "==============================="
        echo "Logging into Conjur..."
        echo "Account: $CONJUR_ACCOUNT"
        echo "Appliance URL: $CONJUR_APPLIANCE_URL"
        echo "Authn Login: $CONJUR_AUTHN_LOGIN"
        echo "==============================="
 
        echo "Authenticating..."
 
        FULL_AUTHN_URL=$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate
        echo "Calling authn URL: $FULL_AUTHN_URL"
        AUTHN_TOKEN=$(curl -s -k --request POST \
        --data "$CONJUR_API_KEY" \
        "$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate" \
        | base64 | tr -d '\r\n')
 
        echo "Full /authenticate response:"
        echo "$AUTHN_TOKEN"
        echo "Authentication successful"
        echo "=============================="
        echo "Fetching secret...."
        SECRET=$(curl -s -k --header "Authorization: Token token=\"$AUTHN_TOKEN\"" \
        "$CONJUR_APPLIANCE_URL/api/secrets/$CONJUR_ACCOUNT/variable/$SECRET_PATH")
 
        SECRET_VALUE=$(echo "$SECRET" | head -n1)
        SECRET_STATUS=$(echo "$SECRET" | tail -n1)        
        echo "Retrieved secret: $SECRET_VALUE"
