name: Terraform Workflow
 
on:
  workflow_call:
    inputs:
      secret-variable-path:
        required: true
        type: string
    secrets:
      conjur-api-key:
        required: true
 
jobs:
  run-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Run Conjur Action
        uses: ConjurAPI/.github/actions/conjur@main
        with:
          api-key: ${{ secrets.conjur-api-key }}
          secret-path: ${{ inputs.secret-variable-path }}
